### ISSUE TITLE
Can't Update TitleKeys

### ISSUE THREAD

**Issue by NamesJoeyWheeler** [Bob123a1/CDNSP-GUI#14]
When I click 'Update Titlekeys', it doesn't update. 
This is what comes up on Python.

_Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000161D789A898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='snip.li', port=80): Max retries exceeded with url: /newkeydb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000161D789A898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Programs\CDNSP-GUI-v4.1\CDNSP-GUI-Bob-v4.1.1.py", line 2885, in threaded_update_titlekeys
    r = requests.get(self.db_URL, allow_redirects=True, verify=False)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\site-packages\requests-2.18.4-py3.6.egg\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='snip.li', port=80): Max retries exceeded with url: /newkeydb (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000161D789A898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))_

Also, when I go on the website (http://snip.li/newkeydb), it seems to be down.

**Comment by Bob123a1** [comment]
Hi,

Check if you have any anti-virus software blocking the site ? Since I know it is blocked for Malwarebytes. 

If you can't access that website then the GUI won't be able to get there updated keys. Just check, the site seems up to me

**Comment by NamesJoeyWheeler** [comment]
Yep, I can't seem to access it.
Perhaps Windows Defender is blocking it (The only anti-virus I have on my PC).

Is there a way to stop it from blocking websites? I couldn't find anything about it.

**Comment by Bob123a1** [comment]
Yeah I would assume it's something to do with your internet, glad to know it's solved now!
