### ISSUE TITLE
Win/OSX - FileNotFoundError: [Errno 2] No translation file found for domain: 'language'

### ISSUE THREAD

**Issue by tobsn** [Bob123a1/CDNSP-GUI#19]
**OSX 10.13.6**
```
❯ python3 CDNSP-GUI-Bob-v4.1.1.py
Traceback (most recent call last):
  File "CDNSP-GUI-Bob-v4.1.1.py", line 78, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=[default_lang])
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CDNSP-GUI-Bob-v4.1.1.py", line 85, in <module>
    set_lang(chosen_lang)
  File "CDNSP-GUI-Bob-v4.1.1.py", line 82, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=["en"])
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'
```

**Windows 10.0.17134 Build 17134**
```
C:\Users\default\Downloads\CDNSP-GUI-master\CDNSP-GUI-master>CDNSP-GUI-Bob.py
Traceback (most recent call last):
  File "C:\Users\default\Downloads\CDNSP-GUI-master\CDNSP-GUI-master\CDNSP-GUI-Bob.py", line 78, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=[default_lang])
  File "C:\Users\default\AppData\Local\Programs\Python\Python37-32\lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\default\Downloads\CDNSP-GUI-master\CDNSP-GUI-master\CDNSP-GUI-Bob.py", line 85, in <module>
    set_lang(chosen_lang)
  File "C:\Users\default\Downloads\CDNSP-GUI-master\CDNSP-GUI-master\CDNSP-GUI-Bob.py", line 82, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=["en"])
  File "C:\Users\default\AppData\Local\Programs\Python\Python37-32\lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'
```

**Comment by Bob123a1** [comment]
@tobsn You would also required the files from v4.1 [Release](https://github.com/Bob123a1/CDNSP-GUI/releases/tag/v4.1)
