### ISSUE TITLE
language for hong kong

### ISSUE THREAD

**Issue by hxxceep** [Bob123a1/CDNSP-GUI#21]
how do I know the language ISO for hong kong?
and I made my translation  files? 

C:\CDNSP-GUI-master>CDNSP-GUI-Bob-v4.1.1.py
Traceback (most recent call last):
  File "C:\CDNSP-GUI-master\CDNSP-GUI-Bob-v4.1.1.py", line 78, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=[default_lang])
  File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\CDNSP-GUI-master\CDNSP-GUI-Bob-v4.1.1.py", line 85, in <module>
    set_lang(chosen_lang)
  File "C:\CDNSP-GUI-master\CDNSP-GUI-Bob-v4.1.1.py", line 82, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=["en"])
  File "C:\Users\ms\AppData\Local\Programs\Python\Python37\lib\gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'

C:\CDNSP-GUI-master>

**Comment by Bob123a1** [comment]
@hxxceep you need to download the zip from v4.1 and extract that into a folder, then place the v4.1.1 script into that v4.1 folder.

**Comment by hxxceep** [comment]
it works even don't have en-hk
