### ISSUE TITLE
No translation file found for domain: 'language'

### ISSUE THREAD

**Issue by ikerib** [Bob123a1/CDNSP-GUI#24]
**Describe the bug**
Can't launch. Everytime I've got No translation file found error

**To Reproduce**
Open in pycharm an run

**Expected behavior**
App working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version Python version 3.5

This is the error:

```
PyDev console: starting.
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
runfile('/home/local/PASAIA/iibarguren/dev/python/CDNSP-GUI/CDNSP-GUI-Bob.py', wdir='/home/local/PASAIA/iibarguren/dev/python/CDNSP-GUI')
Traceback (most recent call last):
  File "/home/local/PASAIA/iibarguren/dev/python/CDNSP-GUI/CDNSP-GUI-Bob.py", line 78, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=[default_lang])
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/opt/pycharm-2018.2.1/helpers/pydev/_pydev_bundle/pydev_umd.py", line 194, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-2018.2.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/local/PASAIA/iibarguren/dev/python/CDNSP-GUI/CDNSP-GUI-Bob.py", line 85, in <module>
    set_lang(chosen_lang)
  File "/home/local/PASAIA/iibarguren/dev/python/CDNSP-GUI/CDNSP-GUI-Bob.py", line 82, in set_lang
    lang = gettext.translation('language', localedir='locales', languages=["en"])
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'language'
```

**Comment by akileos** [comment]
See Issue #19

**Comment by Bob123a1** [comment]
You probably want to set your current directory to the GUI folder
