### ISSUE TITLE
Request rejected by server! Check your cert.

### ISSUE THREAD

**Issue by OXYDER** [Bob123a1/CDNSP-GUI#28]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\SWITCH\CDNSP-GUI-Bobv4\CDNSP-GUI-Bob-v4.1.1.py", line 2193, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "D:\SWITCH\CDNSP-GUI-Bobv4\CDNSP-GUI-Bob-v4.1.1.py", line 2161, in threaded_game_info
    base_ver = get_versions(tid)[-1]
  File "D:\SWITCH\CDNSP-GUI-Bobv4\CDNSP-GUI-Bob-v4.1.1.py", line 691, in get_versions
    j = r.json()
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\OXYDE\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Bob123a1** [comment]
@OXYDER do you still get the same error ? The cert should be automatically downloaded, you deleted "nx_tls_client_cert.pem" right ?

**Comment by shedeus** [comment]
I'm having a similar issue. I tried deleting "nx_tls_client_cert.pem" and let the app download the latest cert.  Here's the text from cmd below:

Current language: en

Checking if all required modules are installed!


Everything looks good!
Request rejected by server! Check your cert.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "CDNSP-GUI-Bob-v4.1.1.py", line 2205, in <lambda>
    tid = self.titleID[t]
  File "CDNSP-GUI-Bob-v4.1.1.py", line 2173, in threaded_game_info
    if i in dir_content:
  File "CDNSP-GUI-Bob-v4.1.1.py", line 703, in get_versions
    versionList = ('%s' % "-".join(str(i) for i in range(0x10000, lastestVer+1, 0x10000))).split('-')
  File "site-packages\requests\models.py", line 892, in json
  File "site-packages\simplejson\__init__.py", line 516, in loads
  File "site-packages\simplejson\decoder.py", line 374, in decode
  File "site-packages\simplejson\decoder.py", line 404, in raw_decode
  File "site-packages\simplejson\scanner.py", line 127, in scan_once
  File "site-packages\simplejson\scanner.py", line 118, in _scan_once
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shedeus** [comment]
Yikes!  Thanks for confirming lol
