### ISSUE TITLE
No translation file found for domain: 'Language'

### ISSUE THREAD

**Issue by BigButton** [Bob123a1/CDNSP-GUI#30]
Traceback (most recent call last):
  File "/Users/justory/Downloads/CDNSP-GUI/CDNSP-GUI-Bob.py", line 78, in set_lang
    lang = gettext.translation('Language', localedir='locales', languages=[default_lang])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'Language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/justory/Downloads/CDNSP-GUI/CDNSP-GUI-Bob.py", line 85, in <module>
    set_lang(chosen_lang)
  File "/Users/justory/Downloads/CDNSP-GUI/CDNSP-GUI-Bob.py", line 82, in set_lang
    lang = gettext.translation('Language', localedir='locales', languages=["en"])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/gettext.py", line 524, in translation
    'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'Language'

**Comment by xjkj123** [comment]
metoo

**Comment by Bob123a1** [comment]
Have you downloaded the files for v4.1 ? You need to extract the files from that and put the v4.1.1 script on the v4.1 folder

**Comment by spraragen88** [comment]
Please make sure you've enter this in the command prompt:
pip3 install requests pyopenssl tqdm unidecode Pillow

If you see errors saying you need to add something to PATH, google how to do so. It takes 5 seconds to setup.

**Comment by zexcster** [comment]
Mac Os, py3.7 Same issue for 4.1.1 copied above 4.1, all modules were installed
