### ISSUE TITLE
download stop when an error has occurred

### ISSUE THREAD

**Issue by esrrhs** [Bob123a1/CDNSP-GUI#31]
can you add an option like "retry download", or just skip to download the next file.

**Comment by esrrhs** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\zx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\zx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "CDNSP-GUI-Bob-v4.1.1.py", line 2785, in threaded_download_all
    download_game(base_tid, base_ver, tkey, nspRepack=self.repack, path_Dir=self.path)
  File "CDNSP-GUI-Bob-v4.1.1.py", line 1073, in download_game
    files, name = download_title(gameDir, tid, ver, tkey, nspRepack, verify)
  File "CDNSP-GUI-Bob-v4.1.1.py", line 869, in download_title
    NCAs[type].append(download_file(url, fPath, fSize))
  File "CDNSP-GUI-Bob-v4.1.1.py", line 785, in download_file
    raise ValueError('Downloaded data is not as big as expected (%s/%s)!' % (dlded, fSize))
ValueError: Downloaded data is not as big as expected (1006632960/1120288768)!

**Comment by cyris69** [comment]
Have a very similar error but it's from just clicking any title. This is from a fresh download of 4.1 with the 4.1.1 file used instead.

```
Current language: en

Checking if all required modules are installed!


Everything looks good!
Persistent queue not found, skipping...
Request rejected by server! Check your cert.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 2193, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 2161, in threaded_game_info
    base_ver = get_versions(tid)[-1]
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 691, in get_versions
    j = r.json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

However also get that cert error on the next game I click.

```
Request rejected by server! Check your cert.
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 2193, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 2161, in threaded_game_info
    base_ver = get_versions(tid)[-1]
  File "C:\Users\user\Desktop\NSW Downloader\CDNSP-GUI-Bob-v4.1.1.py", line 691, in get_versions
    j = r.json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

So I can not create a queue, click download, etc. I've already gotten a full nsp/xci dump of all stuff current to last week from elsewhere so mostly need to get access for Updates/DLC. 

Lastly, thanks for an awesome GUI!

**Comment by Bob123a1** [comment]
@esrrhs Download again, and it should resume and complete it, that error is most likely due to unstable network.
@cyris69 the cert is died, you would need to find another public cert or use your own

**Comment by esrrhs** [comment]
@Bob123a1 yes, can you add an option that can auto download again
