### ISSUE TITLE
Request rejected by server

### ISSUE THREAD

**Issue by willstr88** [Bob123a1/CDNSP-GUI#37]
**Describe the bug**
Whenever I try to get an image for a game or download a game, I get an error in the console, saying "Request rejected by server! Check your cert." All I did was download the 4.1 files and the 4.1.1 py file.

**To Reproduce**
1. Click on any game, or try to download a game
2. Console gives error: 
"Request rejected by server! Check your cert.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "CDNSP-GUI-Bob-v4.1.1.py", line 2193, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "CDNSP-GUI-Bob-v4.1.1.py", line 2161, in threaded_game_info
    base_ver = get_versions(tid)[-1]
  File "CDNSP-GUI-Bob-v4.1.1.py", line 691, in get_versions
    j = r.json()
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

**Expected behavior**
I expected to be able to download a game or a game image

**Screenshots**
The game image box looks like this:
![capture](https://user-images.githubusercontent.com/10049583/44934317-6c363380-ad3a-11e8-9691-26b39d57adef.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 4.1.1

**Comment by mikhailrepka** [comment]
Same problem

**Comment by Bob123a1** [comment]
You would need to find a working public cert or use your own

**Comment by AnakinCzar** [comment]
How would i find a working public cert or create my own ? im having the same issue ever since upgrading to 4.1.1

**Comment by shedeus** [comment]
google.  It was literally the 3rd link from the top for a new, working cert
