### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by 877cms** [Bob123a1/CDNSP-GUI#41]
When downloading NSP using latest 4.1.1 I come back to the PC and it has stopped downloading with the following message:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\877\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\877\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\877\CDNSP-GUI-Bob-v4.1.1.py", line 2882, in threaded_update_titlekeys
    self.status_label.config(text=_("Status: Updating titlekeys"))
  File "C:\Users\877\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1482, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\877\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1473, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main** 

I am using a VPN, could it be a network error?
In which case, can it be made to automatically resume download?

**Comment by Bob123a1** [comment]
Should be fixed in v5!

**Comment by 877cms** [comment]
Thank you!
