### ISSUE TITLE
Exception: b'Failed to convert C:\\Users\\\xcc\xec\xcf\xe8 to UTF-16!'. Code: 1

### ISSUE THREAD

**Issue by SephirothDD** [Bob123a1/CDNSP-GUI#48]
For example
01008fd004db6000 v0:
        Downloading CNMT (2342a45acd24d386d778ace58c6f7b33.cnmt.nca)...
                Saved to 2342a45acd24d386d778ace58c6f7b33.cnmt.nca!
Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\NS\CDNSP GUI Bob v5\CDNSP-GUI-Bob-v5.py", line 2740, in threaded_download
    download_game(base_tid, base_ver, tkey, nspRepack=self.repack, path_Dir=self.path)
  File "D:\NS\CDNSP GUI Bob v5\CDNSP-GUI-Bob-v5.py", line 1119, in download_game
    files, name = download_title(gameDir, tid, ver, tkey, nspRepack, verify)
  File "D:\NS\CDNSP GUI Bob v5\CDNSP-GUI-Bob-v5.py", line 847, in download_title
    cnmtDir = decrypt_NCA(cnmtNCA)
  File "D:\NS\CDNSP GUI Bob v5\CDNSP-GUI-Bob-v5.py", line 580, in decrypt_NCA
    raise Exception(err_msg)
Exception: b'Failed to convert C:\\Users\\\xcc\xec\xcf\xe8 to UTF-16!'. Code: 1

**Comment by dakiz71** [comment]
I also have these problems with 5.0/5.01, obviously the cert.perm is valid since v4.0 works like a charm
windows 10 pro, python 3.70 installed as suggested per your instructions, also read the readme file in cdnsp 5 and executed the command line requested.

this is the error I get when loading game's image
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Micky&Papà\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Micky&Papà\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 2359, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 2314, in threaded_game_info
    result = game_image(tid, base_ver, self.titleKey[self.titleID.index(tid)])
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 1439, in game_image
    cnmtDir = decrypt_NCA(cnmtNCA)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 580, in decrypt_NCA
    raise Exception(err_msg)
Exception: b'Failed to convert C:\\Users\\Micky&Pap\xe0 to UTF-16!'. Code: 1

and this when trying to download a game:
01000320000cc000 v0:
        Downloading CNMT (20aa5d8076d4864d70fb6a46774fc4c8.cnmt.nca)...
                Saved to 20aa5d8076d4864d70fb6a46774fc4c8.cnmt.nca!
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Micky&Papà\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Micky&Papà\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 2742, in threaded_download
    download_game(base_tid, base_ver, tkey, nspRepack=self.repack, path_Dir=self.path)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 1119, in download_game
    files, name = download_title(gameDir, tid, ver, tkey, nspRepack, verify)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 847, in download_title
    cnmtDir = decrypt_NCA(cnmtNCA)
  File "D:\=P2P=\NON TOCCARE\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.1.py", line 580, in decrypt_NCA
    raise Exception(err_msg)
Exception: b'Failed to convert C:\\Users\\Micky&Pap\xe0 to UTF-16!'. Code: 1

**Comment by bouhrassa** [comment]
Also have this bug 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Marc-André\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Marc-André\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Switch\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.2.py", line 2377, in <lambda>
    thread = threading.Thread(target = lambda: self.threaded_game_info(evt))
  File "F:\Switch\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.2.py", line 2331, in threaded_game_info
    result = game_image(tid, base_ver, self.titleKey[self.titleID.index(tid)])
  File "F:\Switch\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.2.py", line 1464, in game_image
    cnmtDir = decrypt_NCA(cnmtNCA)
  File "F:\Switch\CDNSP-GUI-Bob-v5\CDNSP-GUI-Bob-v5.0.2.py", line 583, in decrypt_NCA
    raise Exception(err_msg)
Exception: b'Failed to convert C:\\Users\\Marc-Andr\xe9 to UTF-16!'. Code: 1
```

**Comment by powei94** [comment]
I have this exact same bug due to an `ó` on my user folder name
