### ISSUE TITLE
Error, Unable to make request without the token

### ISSUE THREAD

**Issue by ivn9000** [Bob123a1/CDNSP-GUI#72]
I'm getting this error:

Error, Unable to make request without the token
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\ivn\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\ivn\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\devs\CDNSP\CDNSP-GUI-Bob-v6.py", line 2763, in threaded_download
    ver = get_versions(updateTid)[-1]
  File "C:\devs\CDNSP\CDNSP-GUI-Bob-v6.py", line 735, in get_versions
    j = r.json()
AttributeError: 'NoneType' object has no attribute 'json'

Please help!

**Comment by addictedgmr** [comment]
bob gui does not support downloading anymore due to CDN being dead. It is now used for checking updates. Bob just has not removed the download button yet.

**Comment by Chrisrobbo04** [comment]
Any updates on downloading bob

**Comment by SirDragonClaw** [comment]
Any alternatives?
