### ISSUE TITLE
Cant Start on MAC OS

### ISSUE THREAD

**Issue by bloodf** [Bob123a1/CDNSP-GUI#82]
I've tried to start the script, but can't make it work. I'm using high sierra

```~/Versionamento/CDNSP-GUI » python3 CDNSP-GUI-Bob-v6.py               heitor@Heitors-iMac
Current language: en

Checking if all required modules are installed!


Unable to get required files! Check your internet connection: [HTTP Error 404: Not Found]

Building the current state list... Please wait, this may take some time depending on how many games you have.
Traceback (most recent call last):
  File "CDNSP-GUI-Bob-v6.py", line 4309, in <module>
    main()
  File "CDNSP-GUI-Bob-v6.py", line 4304, in main
    Application(root, titleID_list, titleKey_list, title_list, dbURL, info_list=info_list)
  File "CDNSP-GUI-Bob-v6.py", line 2003, in __init__
    self.update_list(rebuild=True)
  File "CDNSP-GUI-Bob-v6.py", line 2160, in update_list
    titleID_list, titleKey_list, title_list, info_list = read_titlekey_list()
  File "CDNSP-GUI-Bob-v6.py", line 4172, in read_titlekey_list
    f = open("titlekeys.txt", "r", encoding="utf8")
FileNotFoundError: [Errno 2] No such file or directory: 'titlekeys.txt'
```

MacOS High Sierra

**Comment by HEYGUL** [comment]
Same there, any news on this ?

**Comment by Bob123a1** [comment]
I have added a link with the files you will require on the homepage README file, please check that out. @bloodf @HEYGUL

**Comment by HEYGUL** [comment]
It is working for my part, thanks :-)
