### ISSUE TITLE
Error in display

### ISSUE THREAD

**Issue by AzhukOffi** [Bob123a1/CDNSP-GUI#83]
The gui don't display any information and display this  error : 
`Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 4367, in <module>
    main()
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 4362, in main
    Application(root, titleID_list, titleKey_list, title_list, dbURL, info_list=info_list)
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 1880, in __init__
    self.image = Image.open("blank.jpg")
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'blank.jpg'`

How to solve this problem ?

**Comment by BASgamer** [comment]
did you download 6.0 and 6.01 and put them in the same folder?

**Comment by AzhukOffi** [comment]
I tried and it puts me this error
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 4367, in <module>
    main()
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 4362, in main
    Application(root, titleID_list, titleKey_list, title_list, dbURL, info_list=info_list)
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 2006, in __init__
    self.update_list(rebuild=True)
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 2165, in update_list
    titleID_list, titleKey_list, title_list, info_list = read_titlekey_list()
  File "C:\Users\Paul\Desktop\CDNSP-GUI-6.0.1\CDNSP-GUI-Bob.py", line 4205, in read_titlekey_list
    f = open("titlekeys.txt", "r", encoding="utf8")
FileNotFoundError: [Errno 2] No such file or directory: 'titlekeys.txt'

**Comment by RiPPERD** [comment]
does this tool even work anymore? ive tried loads it just keeps throwing errors

**Comment by Bob123a1** [comment]
I have added a link with the files you will require on the homepage README file, please check that out. @AzhukOffi @RiPPERD
